#!/bin/bash

port=4567

install_phantomjs() {
  export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  if [[ $(phantomjs --version) != '2.1.1' ]]; then
    rm -rf travis_phantomjs
    mkdir travis_phantomjs
    wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
    tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs
  fi
}

start_server() {
  mkdir -p log
  bundle exec ruby test/server.rb > log/test.log 2>&1 &
}

run_tests() {
  npm run lint && phantomjs script/runner.js http://localhost:$port/
}

server_started() {
  lsof -i :${1?} >/dev/null
}

timestamp() {
  date +%s
}

wait_for_server() {
  timeout=$(( `timestamp` + $1 ))
  while true; do
    if server_started "$2"; then
      break
    elif [ `timestamp` -gt "$timeout" ]; then
      echo "timed out after $1 seconds" >&2
      exit 1
    fi
  done
}

install_phantomjs
npm run build
start_server
server_pid=$!
wait_for_server 5 $port
run_tests
result=$?
kill $server_pid
exit $result
